[package]
name = "bfs"
version = "0.1.0"
authors = ["owen <stensonowen@gmail.com>"]

[dependencies]
phf = "0.7.20"
wikidata = { path = "../wikidata" }
ironstorm_lookup = "1.0.2"
lazy_static = "0.2.2"
clap = "2.*.0"

