[package]
name = "links"
version = "0.1.0"
authors = ["owen <owen@oms.sh>"]

[dependencies]
fnv = "1.0.5"
clap = "2.20.5"
regex = "0.1.80"
chrono = "0.3.0"

slog = "1.5.2"
slog-term = "1.5.0"

serde = "0.9.9"
serde_json = "0.9.8"
serde_derive = "0.9.9"

csv = "*"
#rayon = "0.6.0"

diesel = { version = "0.11.0", features = ["postgres", "chrono"] }
diesel_codegen = { version = "0.11.0", features = ["postgres"] }
dotenv = "0.8.0"

r2d2 = "0.7.1"
r2d2-diesel = "0.11.0"

rocket = "0.2.2"
rocket_codegen = "0.2.2"

[dependencies.rocket_contrib]
version = "0.2.2"
default-features = false
features = ["tera_templates", "json"]

